<?php
  date_default_timezone_set ('America/Los_Angeles'); 

  define('DB_HOST', 'ix.cs.uoregon.edu:PORT');
  define('DB_NAME', 'db');
  define('DB_CHARSET', 'utf8');
  define('DB_USER', 'CHANGEME');
  define('DB_PASSWORD', 'guest');

  //DEFINE THE TIME INTERVAL (IN SECONDS) IN WHICH THE TRACKER WILL UPDATE 
  //NECESSARY TO SOLVE THE BUG
  define('INTERVAL', 300); //NOTE : UNIT IS SECONDS HERE 

  //DEFINE THE INCUBATION PERIOD BELOW 
  //INCUBATION PERIOD IS THE MAX TIME A PERSON COULD CARRY THE INFECTION GENERALLY ITS 14 DAYS
  //BUT 20 WILL BE BETTER JUST TO BE SAFE 
  define('INCUBATION_PERIOD', 20); //NOTE : UNIT IS DAYS HERE 

  //ENTER THE RISK RADIUS BELOW 
  define('RISK_RADIUS', 10) //NOTE : UNIT IS KILOMETRES HERE 1 KILOMETRES = 1000 METRES
?>
